---
title: "Report"
author: 'Alan Wu, Oscar Su, Sean Gee, Shelby Jackson, Alton Law'
date: "2025-02-25"
output: html_document
---

```{r}
library(tidyverse)
data <- read.csv("cleaned_dataset.csv", header=TRUE) %>% select(-X)
attach(data)
```

Target prediction variable : Mean Hourly Gap just because it looks more normal

# Summary statistics and data exploration

## Distribution of categorical variables
```{r}
company_type <- table(NACE.Letter)
barplot(company_type)

report_years <- table(Report.Year)
barplot(report_years)
```

## Extract variables
```{r}
library(vtable)

new_table <- data.frame(Report.Year, Mean.Hourly.Gap, Median.Hourly.Gap, Q1.Female, Q2.Female, Q3.Female, Q4.Female, Percentage.Employees.Female)

## Descriptive tables
st(new_table, digits=4)

cor(new_table)
pairs(new_table)
```

### Distribution of variables
```{r}
for (col in 2:ncol(new_table)){
  hist(new_table[, col], main=colnames(new_table)[col], xlab=colnames(new_table)[col])
}
```

## initial fit
```{r}
m1 <- lm(Mean.Hourly.Gap ~ Q1.Female + Q2.Female + Q3.Female + Q4.Female + Percentage.Employees.Female)
summary(m1)
```
